server:
  port: 4001
#  servlet.context-path: /
#  servlet.context-path: /approval

#url: jdbc:postgresql://mac:5432/postgres
#username: macpguser
#password: Asdf1234


spring:
  #  local data source
  datasource:
    platform: oracle
    continue-on-error: true
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

    #    url: jdbc:oracle:thin:BREBIFMIS/BREBIFMIS123#@192.168.1.222:1521:orcl
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: approval@fairgroupbd.com
#    username: vbms.erp@gmail.com
    password: A@2021
#    password: xborisdylezlqxlv
    protocol: smtp
    properties:
      mail:
        transport.protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
  data:
    jpa:
      repositories:
        enabled: true
